def create_blackboard(
    project_brief: str = "",
    project_brief_source: str = "",
    source_version: str = "",
    source_artifacts: dict | None = None,
    executive_evaluation: str = "",
):
    """Create a fresh shared blackboard for the V1 workflow."""
    if source_artifacts is None:
        source_artifacts = {
            "project_brief": "",
            "prd": "",
            "architecture": "",
            "gtm": "",
            "blackboard": "",
            "activity_log": "",
        }

    return {
        "project_brief": project_brief,
        "project_brief_source": project_brief_source,
        "source_version": source_version,
        "source_artifacts": source_artifacts,
        "executive_evaluation": executive_evaluation,
        "workflow_stage": "first_pass",
        "prd_draft": "",
        "prd_draft_initial": "",
        "product_initial_draft": "",
        "product_revised_draft": "",
        "product_post_correction_drafts": [],
        "product_locked_draft": "",
        "architecture_notes": "",
        "diagram_blueprint": "",
        "gtm_notes": "",
        "second_pass_draft": "",
        "product_locking": {
            "applied": False,
            "confirmed_in_scope": [],
            "confirmed_deferred": [],
            "confirmed_out_of_scope": [],
            "locking_note": "",
            "raw": "",
            "source": "",
            "parsed": False,
        },
        "arbitration": {
            "retained": [],
            "deferred": [],
            "rejected": [],
            "open_points": [],
            "rationales": [],
            "warnings": [],
            "raw": "",
            "source": "",
            "parsed": False,
            "raw_parsed": {
                "retained": [],
                "deferred": [],
                "rejected": [],
                "open_points": [],
                "rationales": [],
                "warnings": [],
                "raw": "",
                "source": "",
                "parsed": False,
            },
            "reconciled": {
                "retained": [],
                "deferred": [],
                "rejected": [],
                "open_points": [],
                "rationales": [],
                "warnings": [],
                "raw": "",
                "source": "",
                "parsed": False,
            },
            "reconciliation_notes": [],
        },
        "expert_contributions": {
            "tech": {
                "summary": "",
                "decisions": [],
                "recommendations": [],
                "risks": [],
                "open_questions": [],
            },
            "growth": {
                "summary": "",
                "decisions": [],
                "recommendations": [],
                "risks": [],
                "open_questions": [],
            },
        },
        "expert_decisions": {
            "tech": [],
            "growth": [],
        },
        "requested_changes": {
            "tech": [],
            "growth": [],
        },
        "review_summaries": {
            "tech": "",
            "growth": "",
        },
        "applied_changes": [],
        "rejected_changes": [],
        "retained_decisions": [],
        "deferred_decisions": [],
        "open_points": [],
        "unresolved_tensions": [],
        "revision_trace": {
            "initial_prd_draft": "",
            "tech_input": "",
            "growth_input": "",
            "revision_summary": "",
        },
        "second_pass_trace": {
            "initial_revision_draft": "",
            "tech_input": "",
            "growth_input": "",
            "revision_summary": "",
        },
        "workflow_trace": {
            "checkpoints": [],
        },
        "readiness": {
            "product": {
                "status": "",
                "blocking_gaps": [],
                "required_improvements": [],
                "parse_warning": "",
            },
            "tech": {
                "status": "",
                "blocking_gaps": [],
                "required_improvements": [],
                "parse_warning": "",
            },
            "growth": {
                "status": "",
                "blocking_gaps": [],
                "required_improvements": [],
                "parse_warning": "",
            },
            "global": {
                "status": "",
                "blocking_gaps": [],
                "required_improvements": [],
                "known_tags": [],
            },
            "global_status": "",
            "loop_count": 0,
            "max_loops": 2,
            "history": [],
            "correction_tasks": [],
            "final_outcome": "",
            "loop_triggered": False,
        },
        "artifacts": {
            "architecture_markdown_ready": False,
            "architecture_visual_ready": False,
            "architecture_visual_warning": "",
        },
        "known_tags": [],
        "open_questions": [],
        "risks": [],
        "decisions": [],
        "conflicts": [],
        "activity_log": [],
    }
